### ISSUE TITLE
WARNING:root:Lossy conversion from float32 to uint8.

### ISSUE THREAD

**Issue by Zengpr** [idealo/image-super-resolution#3]
WARNING:root:Lossy conversion from float32 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.

**Comment by cfrancesco** [comment]
This was fixed in the new version. Thank you.

**Comment by Samanvay96** [comment]
I am still getting this warning on the latest version, 2.5.0. Is that expected?
